### ISSUE TITLE
Incorrect NPC animations in default Half-Life 2 campaign

### ISSUE THREAD

**Issue by knoxed** [ZehMatt/Lambda#311]
Fresh server install, gamemode from workshop and fresh client install. On trainstation_04 alyx, barney and kleiner have their animations broken. We either break it because we ship our own models of them (which are now obsolete) or it is something else.

Video: (6 years ago but the same issue)
https://www.youtube.com/watch?v=MVHORfWgoSg

Further testing showed that it works on local P2P but not on dedicated (linux) and the same goes being on sandbox gamemode.

Even after further investigation this might seem something for Rubat to fix.

**Comment by knoxed** [comment]
This was resolved a while ago with the issue being on different branches. With the upcoming update hopefully we get rid of all animation issues.

**Comment by OctolingNexus** [comment]
im bumping this. this issue was not resolved still is happening to this day we are both on the same branch.
